from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    PageBreak
)

from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib import colors
from reportlab.lib.units import inch
#from reportlab.pdfbase.pdfmetrics import stringWidth

from datetime import datetime
import os


# =====================================================
# COLORS
# =====================================================

PRIMARY = colors.HexColor("#2563EB")
SECONDARY = colors.HexColor("#1E3A8A")
LIGHT = colors.HexColor("#F8FAFC")
TEXT = colors.HexColor("#374151")
BORDER = colors.HexColor("#D1D5DB")


# =====================================================
# STYLES
# =====================================================

styles = getSampleStyleSheet()


title_style = ParagraphStyle(
    "Title",
    parent=styles["Title"],
    fontName="Helvetica-Bold",
    fontSize=30,
    leading=34,
    textColor=PRIMARY,
    alignment=TA_CENTER,
    spaceAfter=25
)

section_heading = ParagraphStyle(
    "SectionHeading",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=18,
    textColor=colors.HexColor("#2563EB"),
    spaceBefore=18,
    spaceAfter=12
)

subtitle_style = ParagraphStyle(
    "Subtitle",
    parent=styles["Heading2"],
    fontName="Helvetica",
    fontSize=16,
    textColor=TEXT,
    alignment=TA_CENTER,
    spaceBefore=18,
    spaceAfter=15
)

section_style = ParagraphStyle(
    "Section",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=18,
    textColor=PRIMARY,
    spaceAfter=12,
    spaceBefore=15
)

normal_style = ParagraphStyle(
    "Normal",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=10,
    leading=18,
    textColor=TEXT
)

small_style = ParagraphStyle(
    "Small",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=8,
    leading=12,
    textColor=colors.grey
)

# =====================================================
# FOOTER
# =====================================================

def add_footer(canvas, doc):

    canvas.saveState()

    width, height = doc.pagesize

    canvas.setStrokeColor(PRIMARY)

    canvas.line(
        40,
        35,
        width - 40,
        35
    )

    canvas.setFont(
        "Helvetica",
        9
    )

    canvas.setFillColor(colors.grey)

    canvas.drawString(
        45,
        20,
        "Generated by DataInsight AI"
    )

    canvas.drawRightString(
        width - 45,
        20,
        f"Page {doc.page}"
    )

    canvas.restoreState()

# =====================================================
# MAIN FUNCTION
# =====================================================

def create_pdf_report(

    pdf_path,
    dataset_summary,
    ml_result,
    ai_story,
    chart_path=None,
    prediction=None

):

    doc = SimpleDocTemplate(

        pdf_path,

        rightMargin=40,
        leftMargin=40,
        topMargin=45,
        bottomMargin=45

    )

    elements = []

        # =====================================================
    # COVER PAGE
    # =====================================================

    logo_path = "static/images/logo.jpg"

    if os.path.exists(logo_path):

        logo = Image(
            logo_path,
            width=2.2*inch,
            height=2.2*inch
        )

        logo.hAlign = "CENTER"

        elements.append(logo)

        elements.append(Spacer(1,25))

    elements.append(
        Paragraph(
            "DataInsight AI",
            title_style
        )
    )

    elements.append(
        Paragraph(
            "AI Powered Data Storytelling Platform",
            subtitle_style
        )
    )

    elements.append(
        Spacer(1,50)
    )

    elements.append(
        Paragraph(
            "<b>Professional Business Analytics Report</b>",
            section_style
        )
    )

    elements.append(
        Spacer(1,25)
    )

    elements.append(
        Paragraph(
            f"Generated on : {datetime.now().strftime('%d %B %Y')}",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"Generated Time : {datetime.now().strftime('%I:%M %p')}",
            normal_style
        )
    )

    elements.append(
        Spacer(1,260)
    )

    elements.append(
        Paragraph(
            "Confidential • Generated Automatically using Artificial Intelligence",
            small_style
        )
    )

    elements.append(
        PageBreak()
    )

        # =====================================================
    # PAGE 2
    # DATASET SUMMARY
    # =====================================================

    elements.append(
        Paragraph(
            "Dataset Summary",
            section_style
        )
    )

    elements.append(
        Paragraph(
            "This section provides an overview of the uploaded dataset including data quality, structure, and completeness.",
            normal_style
        )
    )

    elements.append(Spacer(1, 18))


    dataset_table = [

        ["Property", "Value"]

    ]

    pretty_names = {

        "Rows": "Total Rows",

        "Columns": "Total Columns",

        "Numeric Columns": "Numeric Columns",

        "Categorical Columns": "Categorical Columns",

        "Missing Values": "Missing Values",

        "Duplicate Rows": "Duplicate Rows"

    }

    for key, value in dataset_summary.items():

        dataset_table.append(

            [

                pretty_names.get(key, key),

                str(value)

            ]

        )


    table = Table(

        dataset_table,

        colWidths=[240, 220]

    )

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),PRIMARY),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("FONTSIZE",(0,0),(-1,-1),10),

            ("BOTTOMPADDING",(0,0),(-1,0),10),

            ("GRID",(0,0),(-1,-1),0.5,BORDER),

            ("BACKGROUND",(0,1),(-1,-1),LIGHT),

            ("TEXTCOLOR",(0,1),(-1,-1),TEXT),

            ("VALIGN",(0,0),(-1,-1),"MIDDLE")

        ])

    )

    elements.append(table)

    elements.append(Spacer(1, 30))

    elements.append(

        Paragraph(

            "Dataset Quality Assessment",

            section_style

        )

    )


    rows = dataset_summary.get("Rows", 0)

    missing = dataset_summary.get("Missing Values", 0)

    duplicate = dataset_summary.get("Duplicate Rows", 0)


    quality = f"""

<b>Observations</b><br/><br/>

• The uploaded dataset contains <b>{rows}</b> records.<br/><br/>

• Missing values detected : <b>{missing}</b><br/><br/>

• Duplicate rows detected : <b>{duplicate}</b><br/><br/>

• The dataset appears suitable for further analysis and machine learning.

"""

    elements.append(

        Paragraph(

            quality,

            normal_style

        )

    )

    elements.append(

        Spacer(1,25)

    )

    elements.append(

        Paragraph(

            "Machine Learning Summary",

            section_style

        )

    )

    elements.append(

        Paragraph(

            "The following table summarizes the trained machine learning model and its evaluation metrics.",

            normal_style

        )

    )

    elements.append(

        Spacer(1,18)

    )


    ignore = [

        "Actual",

        "Predictions",

        "Metadata Path",

        "Model Path",

        "feature_importance",

        "chart"

    ]


    ml_table = [

        [

            "Metric",

            "Value"

        ]

    ]


    for key, value in ml_result.items():

        if key in ignore:

            continue

        ml_table.append(

            [

                key,

                str(value)

            ]

        )


    table = Table(

        ml_table,

        colWidths=[240,220]

    )


    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),PRIMARY),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

            ("GRID",(0,0),(-1,-1),0.5,BORDER),

            ("BACKGROUND",(0,1),(-1,-1),colors.white),

            ("TEXTCOLOR",(0,1),(-1,-1),TEXT),

            ("FONTSIZE",(0,0),(-1,-1),10),

            ("BOTTOMPADDING",(0,0),(-1,0),10)

        ])

    )


    elements.append(table)

    #elements.append(

        #PageBreak()

    #)

        # ----------------------------------------------------
# MODEL PERFORMANCE
# ----------------------------------------------------

    if chart_path and os.path.exists(chart_path):

        #elements.append(PageBreak())

        elements.append(
            Paragraph(
                "4. Model Performance",
                section_heading
            )
        )

        elements.append(Spacer(1, 8))

        elements.append(
            Paragraph(
            """
            The chart below compares the actual values with the predicted
            values produced by the trained machine learning model.
            A smaller gap between the points indicates higher prediction accuracy.
            """,
            normal_style
            )
        )

        elements.append(Spacer(1, 10))

        chart = Image(
            chart_path,
            width=5.8 * inch,
            height=3.8 * inch
        )

        chart.hAlign = "CENTER"

        elements.append(chart)

        elements.append(Spacer(1, 15))

        elements.append(
            Paragraph(
            "Model Interpretation", section_style
            )
        )

        problem = ml_result.get("problem", "")

        if problem == "Regression":

            interpretation = f"""
    • Problem Type : <b>{problem}</b><br/><br/>

    • R² Score : <b>{ml_result.get('r2')}</b><br/>

    • Mean Absolute Error : <b>{ml_result.get('mae')}</b><br/>

    • Root Mean Squared Error : <b>{ml_result.get('rmse')}</b><br/><br/>

    The regression model demonstrates the relationship between
    independent variables and the target variable.
    Higher R² and lower error values indicate better prediction quality.
    """

        else:

            interpretation = f"""
    • Problem Type : <b>{problem}</b><br/><br/>

    • Accuracy : <b>{ml_result.get('accuracy')}%</b><br/>

    • Precision : <b>{ml_result.get('precision')}%</b><br/>

    • Recall : <b>{ml_result.get('recall')}%</b><br/>

    • F1 Score : <b>{ml_result.get('f1')}%</b><br/><br/>

    The classification model successfully categorizes the dataset
    into predefined classes with the above performance metrics.
    """

        elements.append(
            Paragraph(
                interpretation,
                normal_style
            )
    )

    elements.append(Spacer(1,20))

        # =====================================================
    # PAGE 5
    # FUTURE PREDICTION
    # =====================================================

    elements.append(PageBreak())

    elements.append(
        Paragraph(
            "5. Future Prediction",
            section_style
        )
    )

    elements.append(
        Spacer(1,10)
    )

    if prediction is not None:

        prediction_text = f"""

<b>Predicted Value</b>

<br/><br/>

The trained machine learning model predicts the future output as:

<br/><br/>

<font color='#2563EB' size='16'>

<b>{prediction}</b>

</font>

<br/><br/>

This prediction is generated using the trained model and the
values entered by the user.

"""

    else:

        prediction_text = """

No prediction has been generated for this report.

"""

    elements.append(

        Paragraph(

            prediction_text,

            normal_style

        )

    )

    elements.append(

        Spacer(1,25)

    )


    # =====================================================
    # BUSINESS RECOMMENDATIONS
    # =====================================================

    elements.append(

        Paragraph(

            "Business Recommendations",

            section_style

        )

    )

    recommendation = """

• Continue collecting more historical records for improving model performance.<br/><br/>

• Regularly retrain the model whenever new datasets become available.<br/><br/>

• Monitor prediction accuracy over time to detect model drift.<br/><br/>

• Integrate the trained model into real-time dashboards for decision support.<br/><br/>

• Use AI Storytelling together with data visualization to communicate insights effectively.

"""

    elements.append(

        Paragraph(

            recommendation,

            normal_style

        )

    )

    elements.append(

        Spacer(1,25)

    )


    # =====================================================
    # FUTURE SCOPE
    # =====================================================

    elements.append(

        Paragraph(

            "Future Scope",

            section_style

        )

    )

    future = """

Future enhancements planned for DataInsight AI include:

<br/><br/>

• Automatic dashboard generation.

<br/><br/>

• Interactive AI chatbot with memory.

<br/><br/>

• Time-series forecasting.

<br/><br/>

• Deep Learning model integration.

<br/><br/>

• Business KPI monitoring.

<br/><br/>

• Cloud deployment with collaborative reporting.

"""

    elements.append(

        Paragraph(

            future,

            normal_style

        )

    )

    elements.append(

        Spacer(1,35)

    )


    # =====================================================
    # END NOTE
    # =====================================================

    elements.append(

        Paragraph(

            "<b>Thank You</b>",

            section_style

        )

    )

    elements.append(

        Paragraph(

            """
This report has been automatically generated by <b>DataInsight AI</b>,
an AI-powered data storytelling platform designed to transform raw
datasets into meaningful business insights.

The results presented in this report are based on the uploaded data
and the selected machine learning model.

""",

            normal_style

        )

    )

        # =====================================================
    # BUILD PDF
    # =====================================================

    doc.build(

        elements,

        onFirstPage=add_footer,

        onLaterPages=add_footer

    )

    return pdf_path